# Generated by Django 2.0 on 2018-06-12 17:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='test_mask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='test_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='项目名称')),
                ('start_time', models.DateTimeField(default=datetime.datetime(2018, 6, 12, 17, 55, 51, 855895), verbose_name='开始时间')),
                ('create_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='责任人')),
            ],
            options={
                'verbose_name': '项目管理',
                'verbose_name_plural': '项目管理',
            },
        ),
        migrations.CreateModel(
            name='test_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='任务名称')),
                ('start_time', models.DateTimeField(auto_now=True, verbose_name='开始时间')),
                ('status', models.IntegerField(choices=[(1, '未开始'), (2, '进行中'), (3, '阻塞'), (4, '完成')], default=1)),
                ('res_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='责任人')),
            ],
            options={
                'verbose_name': '任务管理',
                'verbose_name_plural': '任务管理',
            },
        ),
        migrations.CreateModel(
            name='test_version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='版本名称')),
                ('status', models.BooleanField(verbose_name='状态')),
                ('start_time', models.DateTimeField(default=datetime.datetime(2018, 6, 12, 17, 55, 51, 856895), verbose_name='开始时间')),
                ('desc', models.CharField(max_length=256, verbose_name='描述')),
                ('create_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='责任人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testmanage.test_project', verbose_name='项目名称')),
            ],
            options={
                'verbose_name': '版本管理',
                'verbose_name_plural': '版本管理',
            },
        ),
        migrations.AddField(
            model_name='test_task',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testmanage.test_version', verbose_name='版本名称'),
        ),
        migrations.AlterUniqueTogether(
            name='test_version',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='test_task',
            unique_together={('version', 'name')},
        ),
    ]
