# Generated by Django 2.0 on 2018-06-13 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='test_project',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 13, 10, 14, 41, 763054), verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='test_task',
            name='status',
            field=models.IntegerField(choices=[(1, '未开始'), (2, '进行中'), (3, '阻塞'), (4, '完成')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='test_version',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 13, 10, 14, 41, 764054), verbose_name='开始时间'),
        ),
    ]
