# Generated by Django 2.0 on 2018-06-13 10:30

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testmanage', '0002_auto_20180613_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_11',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=64, verbose_name='任务名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test_project',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 13, 10, 30, 44, 131098), verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='test_version',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 13, 10, 30, 44, 132098), verbose_name='开始时间'),
        ),
    ]
