# Generated by Django 2.0 on 2018-06-13 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmanage', '0004_auto_20180613_1034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test_mask',
        ),
        migrations.AlterField(
            model_name='test_project',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 13, 10, 36, 16, 659118), verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='test_version',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 13, 10, 36, 16, 660118), verbose_name='开始时间'),
        ),
    ]
