# Generated by Django 2.0 on 2018-06-13 10:58

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testmanage', '0005_auto_20180613_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_project',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 13, 10, 58, 4, 145902), verbose_name='开始时间'),
        ),
        migrations.RemoveField(
            model_name='test_task',
            name='res_person',
        ),
        migrations.AddField(
            model_name='test_task',
            name='res_person',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='参与者'),
        ),
        migrations.AlterField(
            model_name='test_version',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 13, 10, 58, 4, 146902), verbose_name='开始时间'),
        ),
    ]
