# Generated by Django 2.0 on 2018-06-13 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmanage', '0007_auto_20180613_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_project',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 13, 15, 2, 58, 853391), verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='test_version',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 13, 15, 2, 58, 854391), verbose_name='开始时间'),
        ),
    ]
