# Generated by Django 2.0 on 2018-06-13 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmanage', '0008_auto_20180613_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_project',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 13, 15, 9, 1, 790150), verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='test_version',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 13, 15, 9, 1, 791150), verbose_name='开始时间'),
        ),
    ]
