# Generated by Django 2.0 on 2018-07-12 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmanage', '0010_auto_20180613_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_project',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 12, 11, 39, 7, 703728), verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='test_version',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 12, 11, 39, 7, 704728), verbose_name='开始时间'),
        ),
    ]
