# Generated by Django 2.0 on 2018-07-20 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmanage', '0011_auto_20180712_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_project',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 20, 15, 47, 53, 833123), verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='test_version',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 20, 15, 47, 53, 833123), verbose_name='开始时间'),
        ),
    ]
