# Generated by Django 2.0 on 2018-07-20 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmanage', '0013_auto_20180720_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_project',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 20, 15, 59, 42, 799673), verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='test_version',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 20, 15, 59, 42, 800674), verbose_name='开始时间'),
        ),
    ]
