# Generated by Django 2.0 on 2018-06-13 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testmanage', '0008_auto_20180613_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='用例名称')),
                ('prepro', models.TextField(max_length=128, verbose_name='前置条件')),
                ('priority', models.IntegerField(choices=[(1, '高'), (2, '中'), (3, '低')], default=1, verbose_name='优先级')),
                ('proceduer', models.TextField(max_length=256, verbose_name='测试步骤')),
                ('result', models.TextField(max_length=256, verbose_name='预期结果')),
                ('remark', models.TextField(max_length=128, verbose_name='备注')),
                ('projecet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testmanage.test_project', verbose_name='项目名称')),
            ],
            options={
                'verbose_name': '项目管理',
                'verbose_name_plural': '项目管理',
            },
        ),
    ]
