# Generated by Django 2.0 on 2018-06-13 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casemanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': '测试用例', 'verbose_name_plural': '测试用例'},
        ),
        migrations.RenameField(
            model_name='case',
            old_name='projecet',
            new_name='project',
        ),
    ]
