# Generated by Django 2.0 on 2018-07-12 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testmanage', '0011_auto_20180712_1139'),
        ('casemanage', '0003_auto_20180613_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='UIAuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='自动化版本名称')),
                ('remark', models.TextField(blank=True, max_length=128, verbose_name='备注')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testmanage.test_project', verbose_name='项目名称')),
            ],
            options={
                'verbose_name': 'UI自动化',
                'verbose_name_plural': 'UI自动化',
            },
        ),
    ]
