# Generated by Django 2.0 on 2018-07-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casemanage', '0004_uiauto'),
    ]

    operations = [
        migrations.CreateModel(
            name='case_catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_business', models.IntegerField(blank=True, null=True, verbose_name='上级分类')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='用例名称')),
                ('info', models.TextField(blank=True, max_length=200, null=True, verbose_name='用例说明')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '用例分类',
                'verbose_name_plural': '用例分类',
            },
        ),
    ]
