# Generated by Django 2.0 on 2018-07-20 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casemanage', '0005_case_catagory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case_catagory',
            old_name='upper_business',
            new_name='upper_case',
        ),
    ]
