# Generated by Django 2.0 on 2018-07-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casemanage', '0006_auto_20180720_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_catagory',
            name='info',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='分类说明'),
        ),
        migrations.AlterField(
            model_name='case_catagory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='分类名称'),
        ),
    ]
