# Generated by Django 2.0 on 2018-09-27 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casemanage', '0008_auto_20180927_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case_catagory',
            options={'verbose_name': '功能', 'verbose_name_plural': '功能菜单'},
        ),
    ]
